# Generated by Django 3.2.4 on 2021-07-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyclone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.TextField()),
                ('category', models.CharField(default='', max_length=100)),
                ('artist1', models.TextField()),
                ('image1', models.ImageField(default='', upload_to='')),
                ('audio_file1', models.FileField(blank=True, null=True, upload_to='')),
                ('audio_link1', models.CharField(blank=True, max_length=200, null=True)),
                ('duration1', models.CharField(max_length=20)),
            ],
        ),
    ]
